### PR TITLE
Add basic circle.yml.

### PR DESCRIPTION
**Pull request by tomwilkie**

### CODE REVIEW

**Comment by dpw** [comment]
Who asked for this?  Both me and Mike rely on running the "go test" tests locally throughout development.  So it's not clear what benefit circleci integration brings at this point in time.

**Comment by awh** [comment]
You might want to revisit this for automatically publishing your site docs to wordpress #41.

**Comment by dpw** [comment]
"automatically publishing site docs" does not necessarily imply circle.

**Comment by awh** [comment]
> "automatically publishing site docs" does not necessarily imply circle.

Hence 'might'.

**Pull request closed without merging**
