### PR TITLE
Docs in wordepress

### PR DESCRIPTION
**Pull request by awh**
Fewer Jekylls, moar Wordepress.

### CODE REVIEW

**Comment by awh** [comment]
This is a purely mechanical conversion of the existing docs into the wordepress site format - over to @abuehrle.

**Comment by dpw** [comment]
I don't mind losing the jekyll stuff, as long as it is replaced by some other reasonably convenient way to preview doc changes.  Can you suggest how that might work?  Ideally it would be some canned mechanism that can be invoked through `make site` or similar (perhaps using your dockerized wordpress?).

**Comment by abuehrle** [comment]
@dpw the plugin is really simple to use and it's very fast.  Changes can be easily viewed on the dev server.  Or yes, you can download the containerized version and build the site locally on your machine.  But, I don't think it's necessary to do that since we do have a dev server setup that lets you preview changes before they get pushed to the live server. 

The plugin can be used on the command line and has a pretty extensive list of commands. The only thing you need is a WP login and then API credentials for the plugin, which are generated from your WP user profile, as described here: 

https://github.com/weaveworks/wordepress

If you're not building the local version, you can ignore, "Configuring Wordpress" section.

**Comment by squaremo** [comment]
> Changes can be easily viewed on the dev server.

For us, yes, but not for any prospective contributors. Though that would be in the "nice problem to have" category at this point.

**Comment by dpw** [comment]
> For us, yes

Not even that, really.  `make site` comes up quickly enough that editing the docs is only at a small remove from WYSIWYG, and the docs can be previewed in mid-edit.  That seems unlikely to be the case for the dev server.

**Comment by awh** [comment]
To be clear, this PR is a WIP to give you early visibility. Some issues:

* I didn't rewrite intra-site page links yet to conform to what the [wordepress tool expects](https://github.com/weaveworks/wordepress#repo-format) (an alternative would be to fix weaveworks/wordepress#8)
* `{:toc}` isn't supported by wordepress
* Setting up wordpress.local as a solution for local preview is currently [an enormous faff](https://github.com/weaveworks/wordpress.local#setup) - there are some issues (weaveworks/wordpress.local#1, weaveworks/wordpress.local#2) to address this, however the use of commercial plugins means we can't share it externally

In terms of invoking the tool to publish release docs, you're free to do that however you like. Net and Scope will be using CircleCI, you can run it manually if you prefer.

**Comment by awh** [comment]
> make site comes up quickly enough that editing the docs is only at a small remove from WYSIWYG, and the docs can be previewed in mid-edit. That seems unlikely to be the case for the dev server.

The manual publish I did for you to the dev server took 30s:

```
$ wordepress --url https://dev-weavewww.pantheonsite.io ... --product flux --version 0.2.0 publish site
2016/04/25 20:07:23 Loading 9 markdown files from site
2016/04/25 20:07:23 Loading page 1 from https://dev-weavewww.pantheonsite.io/wp-json/wp/v2/documentation
2016/04/25 20:07:24 Uploading document: flux-0-2-0-daemon
2016/04/25 20:07:26 Uploading document: flux-0-2-0-edgebal
2016/04/25 20:07:28 Uploading document: flux-0-2-0-fluxctl
2016/04/25 20:07:30 Uploading document: flux-0-2-0-getstarted
2016/04/25 20:07:32 Uploading document: flux-0-2-0-index
2016/04/25 20:07:34 Uploading document: flux-0-2-0-overview
2016/04/25 20:07:36 Uploading document: flux-0-2-0-prometheus
2016/04/25 20:07:38 Uploading document: flux-0-2-0-swarm
2016/04/25 20:07:40 Uploading document: flux-0-2-0-web
2016/04/25 20:07:42 Uploading image: 787e2cea1343facce26cfb4058d240c9bf6b70a7.png
2016/04/25 20:07:45 Uploading image: 96888487dd382b37d445ff632410c3024d7b1b4c.png
2016/04/25 20:07:48 Uploading image: b3e327b721b1ebf9970e1d45fdc782cf9e830ba5.jpg
2016/04/25 20:07:51 Uploading image: 284ec2f6f89c8e2b6166f21c88e2b0e41f568b1d.jpg
2016/04/25 20:07:53 Uploading image: 34937ec1ecf318dbe69b69b63dd9fdb0f0347ec4.jpg
```

Publish is differential though - here's what happens when I republish to the dev server without making changes to the source:

```
$ wordepress --url https://dev-weavewww.pantheonsite.io ... --product flux --version 0.2.0 publish site
2016/04/26 11:11:09 Loading 9 markdown files from site
2016/04/26 11:11:09 Loading page 1 from https://dev-weavewww.pantheonsite.io/wp-json/wp/v2/documentation
2016/04/26 11:11:11 Loading page 2 from https://dev-weavewww.pantheonsite.io/wp-json/wp/v2/documentation
2016/04/26 11:11:12 Skipping document: flux-0-2-0-daemon
2016/04/26 11:11:12 Skipping document: flux-0-2-0-edgebal
2016/04/26 11:11:12 Skipping document: flux-0-2-0-fluxctl
2016/04/26 11:11:12 Skipping document: flux-0-2-0-getstarted
2016/04/26 11:11:12 Skipping document: flux-0-2-0-index
2016/04/26 11:11:12 Skipping document: flux-0-2-0-overview
2016/04/26 11:11:12 Skipping document: flux-0-2-0-prometheus
2016/04/26 11:11:12 Updating document: flux-0-2-0-swarm
2016/04/26 11:11:13 Skipping document: flux-0-2-0-web
2016/04/26 11:11:13 Skipping image: 787e2cea1343facce26cfb4058d240c9bf6b70a7.png
2016/04/26 11:11:13 Skipping image: 96888487dd382b37d445ff632410c3024d7b1b4c.png
2016/04/26 11:11:14 Skipping image: b3e327b721b1ebf9970e1d45fdc782cf9e830ba5.jpg
2016/04/26 11:11:14 Skipping image: 284ec2f6f89c8e2b6166f21c88e2b0e41f568b1d.jpg
2016/04/26 11:11:14 Skipping image: 34937ec1ecf318dbe69b69b63dd9fdb0f0347ec4.jpg
```

**Comment by awh** [comment]
weaveworks/wordepress#24 is another possibility for preview that would also satisfy the external contributor requirement.

**Comment by awh** [comment]
weaveworks/wordepress#25

**Comment by abuehrle** [comment]
Why would an external contributor need to preview the wordpress site?  I just made some PRs to Google and I was only able to preview them in github.   I would think a contributor to our docs would go through a similar process, make a PR, we review it, then it gets merged, and uploaded to the live site from github.  What were you envisioning that's different from this? 

I would not be comfortable giving an external contributor any sort of access to our website anyway.

**Comment by squaremo** [comment]
> Why would an external contributor need to preview the wordpress site?

@abuehrle Whom are you asking? I would like an external contributor to be able to preview changes they have made to documentation without depending on our installation of wordpress, to be clear.

**Comment by abuehrle** [comment]
Can't they do that in Github at the moment? As I said over at google, that's the way it's done. I don't see the final result on their website, just in the github file.

**Comment by dpw** [comment]
> Can't they do that in Github at the moment?

We've tried to make is easy for people (whether ourselves or outside contributors) to build and test code changes, so that it is easy to develop and contribute high-quality code changes.

In a similar way, it should be easy for people to preview doc changes, with a reasonable degree of fidelity, so that it is easy to develop and contribute high-quality doc changes.

The internal vs outside contributors things is a bit of a red herring, in that sense.

**Comment by awh** [comment]
@dpw @squaremo some questions:

* Is a 5s incremental publish to dev-weavewww.pantheonsite.io a good enough replacement for `make site` in the short term to get this moving forward?
* Net/Scope will have automated publishing of master and feature branches to dev-weavewww and of release docs to weave.works via Circle. What are your thoughts on automated publishing for Flux?

**Comment by dpw** [comment]
> Is a 5s incremental publish to dev-weavewww.pantheonsite.io a good enough replacement for make site in the short term

It might do as a stopgap, but has the drawback of only allowing one person to work on the docs at once, no?

>  to get this moving forward?

You're talking as if this is your responsibility.  I'm not sure how that became the case, or whether it is beneficial.  If you've provided adequate documentation for wordepress and a working example of its use in the form of weave net, why shouldn't it be up to those working on flux to move things forward?

>     Net/Scope will have automated publishing of master and feature branches to dev-weavewww and of release docs to weave.works via Circle. What are your thoughts on automated publishing for Flux?

There should be an automated means of publishing the flux docs, in the sense of a command that does it (when supplied with the necessary credentials).  I don't think how that command gets invoked is something to get hung up on (it might be by hand, or as part of a release script, or as part of some CI system).

**Comment by abuehrle** [comment]
@squaremo Very minor edits were made here.   I guess I need to rebase to resolve the conflicts and then we can merge.

**Pull request merged**
